* Godot Fluidsynth

** DEFER README
:PROPERTIES:
:ID:       9143f0ac-4efc-4139-9114-705d9ce2a0c0
:END:
rename this subtree something more semantic like "Overview" and configure it to export to README.md. Convert the following markdown to Org format.
#+begin_src markdown :tangle README.md
godot-gdnative-fluidsynth
=========================

Godot gdnative fluidsynth library to allow playing music using fluidsynth. Provides some primitives like ~AudioStreamMidiTrack~ and ~EventStreamMidiTrack~.

## Contents
,* godot-cpp as a submodule (`godot-cpp/`)
,* GitHub Issues template (`.github/ISSUE_TEMPLATE.yml`)
,* GitHub CI/CD workflows to publish your library packages when creating a release (`.github/workflows/builds.yml`)
,* preconfigured source files for C++ development of the GDExtension (`src/`)
,* setup to automatically generate `.xml` files in a `doc_classes/` directory to be parsed by Godot as [GDExtension built-in documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_docs_system.html)


### Configuring an IDE
You can develop your own extension with any text editor and by invoking scons on the command line, but if you want to work with an IDE (Integrated Development Environment), you can use a compilation database file called `compile_commands.json`. Most IDEs should automatically identify this file, and self-configure appropriately.
To generate the database file, you can run one of the following commands in the project root directory:
```shell
# Generate compile_commands.json while compiling
scons compiledb=yes

# Generate compile_commands.json without compiling
scons compiledb=yes compile_commands.json
```

## Usage - Actions

This repository comes with a GitHub action that builds the GDExtension for cross-platform use. It triggers automatically for each pushed change. You can find and edit it in [builds.yml](.github/workflows/builds.yml).
After a workflow run is complete, you can find the file `godot-cpp-template.zip` on the `Actions` tab on GitHub.

## Old README


How to Install
--------------

Install system dependencies for Ubuntu:

    apt install fluidsynth libfluidsynth-dev abcmidi scons

Build
-----

Initialize git submodules:

    git submodule update --init --recursive

Create assets:

    make assets

Compile godot-cpp library:

    make godot-cpp

Compile gdnative library:

    make
#+end_src

** Godot 4.5 Migration Summary

*** Overview
Migration of godot-gdnative-fluidsynth from Godot 3 (GDNative) to Godot 4.5 (GDExtension).

*** Commits on godot-4.5 branch (14 total)

**** Phase 1: Initial Setup
- ba31511 :: checkout godot-cpp/tags/godot-4.5-stable
- bd1dae4 :: update build instructions (added fluidsynth/scons deps for Ubuntu)
- 0c11181 :: convert project to v4 with godot's migration tool
- 3431b9c :: update godot-cpp to 4.5-stable (.gitmodules)
- 1f86e70 :: update .gitignore

**** Phase 2: GDExtension Template Integration
- 1177227 :: example register_types (new register_types.cpp/h)
- 520202c :: most of the example files from the gdextension template repo
  - Added .clang-format, .editorconfig, CMakeLists.txt
  - Added GitHub workflows for CI/CD
  - Added extension_api.json
  - Added godot-midi/ demo project structure

**** Phase 3: Code Migration
- a02ad90 :: update godot-cpp submodule version to 4.5-stable
- 7df3307 :: it builds; there is finish work left
  - Removed src/gdlibrary.cpp (GDNative entry point - obsolete)
  - Updated SConstruct build system
  - Modified all source files for GDExtension API:
    - gdmidiplayer.cpp/h
    - midi_file_reader.cpp/h
    - soundfont_file_reader.cpp/h
    - register_types.cpp/h

**** Phase 4: Polish & Fixes
- 74c02fa :: README contains info that should be issues etc
- 02ce372 :: edits to gdscript to get it to open in Godot Editor locally
  - Updated addon scripts for Godot 4 API
  - Added .uid files for resources
  - Fixed icon.svg.import
- 0458e00 :: fix some translation errors in .clang-format
- 7fb4107 :: format cpp files with new rules
- da9da75 :: use AudioServer mix_rate in gdmidiplayer::init()
- d75bcda :: checkout godot-cpp to godot-4.5 branch

*** Key API Changes (GDNative → GDExtension)

**** Class Registration
- Old: ~godot_nativescript_init()~ with manual bindings
- New: ~GDREGISTER_CLASS()~ in ~register_types.cpp~

**** Header Includes
- Old: ~#include <Godot.hpp>~, ~#include <Reference.hpp>~
- New: ~#include <godot_cpp/...>~ namespaced headers

**** Class Inheritance
- Old: ~class GDMidiPlayer : public AudioStreamPlayer~
- New: Uses ~GDCLASS()~ macro, ~ClassDB::bind_method()~

**** Entry Point
- Old: ~gdlibrary.cpp~ with ~godot_gdnative_init~
- New: ~register_types.cpp~ with GDExtension initialization

*** Files Changed Summary

| Category         | Files Modified/Added                                      |
|------------------+-----------------------------------------------------------|
| Build System     | SConstruct, CMakeLists.txt                                |
| Source Code      | gdmidiplayer.cpp/h, midi_file_reader.cpp/h                |
|                  | soundfont_file_reader.cpp/h, register_types.cpp/h         |
| Removed          | gdlibrary.cpp (obsolete GDNative entry)                   |
| GDScript Addons  | addons/midi/*.gd (API updates, added .uid files)          |
| Project Config   | project.godot, *.gdextension                              |
| Tooling          | .clang-format, .editorconfig, .github/workflows/builds.yml|

*** TODO Current Status
:PROPERTIES:
:ID:       4e3a4851-6625-4df5-8559-7d711aed5379
:END:
- [X] Project converts with Godot migration tool
- [X] godot-cpp submodule updated to 4.5-stable
- [X] Build system updated (SConstruct)
- [X] Source files compile with GDExtension API
- [X] GDScript addons updated for Godot 4
- [X] AudioServer mix_rate used in initialization


**** TODO - [ ] CI/CD workflow verification
:PROPERTIES:
:ID:       28ba97c0-742d-43fe-8e5e-4b2521f4d93c
:END:
Right now I have two errors:
#+begin_src markdown
- [ ] `scons: *** [godot-cpp/gen/include/godot_cpp/core/ext_wrappers.gen.inc] Exception : Cannot do a precision=double build using 'godot-cpp/gdextension/extension_api.json' which was generated by Godot built with precision=single`
This error is an upstream problem and is happening on a ton of the builds.
I currently suspect https://github.com/godotengine/godot-cpp/issues/1729 is relevant.
- [ ] ` In file included from src/gdmidiplayer.cpp:1:
src/gdmidiplayer.h:12:10: fatal error: fluidsynth.h: No such file or directory
   12 | #include <fluidsynth.h>
      |          ^~~~~~~~~~~~~~`
#+end_src


**** DEFER - [ ] Runtime testing (to be verified)
:PROPERTIES:
:ID:       9f1642a1-599e-4bd9-aa6c-abee01e9c2c4
:END:
Let's port over Godot MIDI Player's test UI. Possibly orchestrate it with gdunit.

**** DEFER cleanup
:PROPERTIES:
:ID:       3ab19126-20e6-4a13-8d75-a44fb0931c74
:END:

**** DEFER documentation
:PROPERTIES:
:ID:       7b84516d-82ac-482c-a71b-980e727cb6f1
:END:
